### ISSUE TITLE
apache2-utils for suse

### ISSUE THREAD

**Issue by beco9292** [redguide/htpasswd#21]
Hi,

I tried with opensuse and sles the cookbook as well, but there wasn't httpd-tools package there, only apache2-utils. My suggestion would be in default.rb attribute file:
 
from
`default['htpasswd']['packages'] = value_for_platform_family(
  ['rhel', 'fedora', 'suse'] => ['httpd-tools'],
  ['default', 'debian'] => ['apache2-utils']
)`

to
`default['htpasswd']['packages'] = value_for_platform_family(
  ['rhel', 'fedora'] => ['httpd-tools'],
  ['default', 'debian', 'suse'] => ['apache2-utils']
)`

Thanks and regards
Béla Szabó

**Comment by guilhem** [comment]
@beco9292 don't hesitate to do a pull request :)
