### ISSUE TITLE
Outdated version in supermarket - upload needed

### ISSUE THREAD

**Issue by pgrzesik** [redguide/htpasswd#28]
Hello, I'm wondering if it would be possible to upload current version of this cookbook to supermarket.chef.io ? That would be awesome and if I can help somehow, I'll gladly do so.

**Comment by micmicsuarez** [comment]
Hi all,

The htpasswd in the chef supermarket is outdated. I am willing to help in testing and uploading the new version of htpasswd coobook.

Thanks,
Michael

**Comment by guilhem** [comment]
0.3.0 released
